In [14]:
import pandas as pd

ADULT_URL = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

adult_df = pd.read_csv(ADULT_URL, header=None)

adult_df.columns = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education_num",
    "marital_status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital_gain",
    "capital_loss",
    "hours_per_week",
    "native_country",
    "income_class"
]

missing_workclass      = (adult_df.workclass == " ?")
missing_occupation     = (adult_df.occupation == " ?")
missing_native_country = (adult_df.native_country == " ?")

In [18]:
indices = np.array(list(adult_df.index))

In [19]:
indices[:20]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
adult_df.workclass.mask(missing_workclass, indices)

0                State-gov
1         Self-emp-not-inc
2                  Private
3                  Private
4                  Private
5                  Private
6                  Private
7         Self-emp-not-inc
8                  Private
9                  Private
10                 Private
11               State-gov
12                 Private
13                 Private
14                 Private
15                 Private
16        Self-emp-not-inc
17                 Private
18                 Private
19        Self-emp-not-inc
20                 Private
21                 Private
22             Federal-gov
23                 Private
24                 Private
25               Local-gov
26                 Private
27                      27
28                 Private
29                 Private
               ...        
32531                32531
32532              Private
32533              Private
32534              Private
32535              Private
32536              Private
3

In [21]:
import numpy as np

In [24]:
adult_df.workclass.mask(~missing_workclass, np.nan)

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
6        NaN
7        NaN
8        NaN
9        NaN
10       NaN
11       NaN
12       NaN
13       NaN
14       NaN
15       NaN
16       NaN
17       NaN
18       NaN
19       NaN
20       NaN
21       NaN
22       NaN
23       NaN
24       NaN
25       NaN
26       NaN
27         ?
28       NaN
29       NaN
        ... 
32531      ?
32532    NaN
32533    NaN
32534    NaN
32535    NaN
32536    NaN
32537    NaN
32538    NaN
32539      ?
32540    NaN
32541      ?
32542      ?
32543    NaN
32544    NaN
32545    NaN
32546    NaN
32547    NaN
32548    NaN
32549    NaN
32550    NaN
32551    NaN
32552    NaN
32553    NaN
32554    NaN
32555    NaN
32556    NaN
32557    NaN
32558    NaN
32559    NaN
32560    NaN
Name: workclass, Length: 32561, dtype: object

In [ ]:
adult_df.workclass = adult_df.workclass.mask(missing_workclass, np.nan)
adult_df.occupation = adult_df.workclass.mask(missing_occupation, np.nan)
adult_df.native_country = adult_df.workclass.mask(missing_native_country, np.nan)

In [1]:
adult_df.dropna().shape

In [ ]:
le_workclass = LabelEncode()
le_occupation = LabelEncode()
le_native_country = LabelEncode()
adult_df.workclass = le_workclass.fit_transform(adult_df.workclass)

In [2]:
((adult_df.workclass == " ?").sum(),
 (adult_df.occupation == " ?").sum(),
 (adult_df.native_country == " ?").sum())

(1836, 1843, 583)

In [4]:
adult_df[missing_workclass | missing_occupation | missing_native_country].shape

(2399, 15)

In [5]:
import numpy as np

In [6]:
mask_1 = np.array([True, False, False, False])
mask_2 = np.array([False, True, False, False])
mask_3 = np.array([False, False, True, False])
mask_1 | mask_2 | mask_3

array([ True,  True,  True, False])

In [7]:
adult_df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income_class      object
dtype: object

In [8]:
for col in adult_df.columns:
    print(col)
    print(adult_df[col].unique())
    print(" ?" in adult_df[col].unique())
    print()

age
[39 50 38 53 28 37 49 52 31 42 30 23 32 40 34 25 43 54 35 59 56 19 20 45
 22 48 21 24 57 44 41 29 18 47 46 36 79 27 67 33 76 17 55 61 70 64 71 68
 66 51 58 26 60 90 75 65 77 62 63 80 72 74 69 73 81 78 88 82 83 84 85 86
 87]
False

workclass
[' State-gov' ' Self-emp-not-inc' ' Private' ' Federal-gov' ' Local-gov'
 ' ?' ' Self-emp-inc' ' Without-pay' ' Never-worked']
True

fnlwgt
[ 77516  83311 215646 ...  34066  84661 257302]
False

education
[' Bachelors' ' HS-grad' ' 11th' ' Masters' ' 9th' ' Some-college'
 ' Assoc-acdm' ' Assoc-voc' ' 7th-8th' ' Doctorate' ' Prof-school'
 ' 5th-6th' ' 10th' ' 1st-4th' ' Preschool' ' 12th']
False

education_num
[13  9  7 14  5 10 12 11  4 16 15  3  6  2  1  8]
False

marital_status
[' Never-married' ' Married-civ-spouse' ' Divorced'
 ' Married-spouse-absent' ' Separated' ' Married-AF-spouse' ' Widowed']
False

occupation
[' Adm-clerical' ' Exec-managerial' ' Handlers-cleaners' ' Prof-specialty'
 ' Other-service' ' Sales' ' Craft-repair' ' Transpor

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  after removing the cwd from sys.path.


In [9]:
adult_df.workclass.value_counts()

 Private             22696
 Self-emp-not-inc     2541
 Local-gov            2093
 ?                    1836
 State-gov            1298
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: workclass, dtype: int64

In [10]:
adult_df.occupation.value_counts()

 Prof-specialty       4140
 Craft-repair         4099
 Exec-managerial      4066
 Adm-clerical         3770
 Sales                3650
 Other-service        3295
 Machine-op-inspct    2002
 ?                    1843
 Transport-moving     1597
 Handlers-cleaners    1370
 Farming-fishing       994
 Tech-support          928
 Protective-serv       649
 Priv-house-serv       149
 Armed-Forces            9
Name: occupation, dtype: int64

In [11]:
adult_df['native_country'].value_counts()

 United-States                 29170
 Mexico                          643
 ?                               583
 Philippines                     198
 Germany                         137
 Canada                          121
 Puerto-Rico                     114
 El-Salvador                     106
 India                           100
 Cuba                             95
 England                          90
 Jamaica                          81
 South                            80
 China                            75
 Italy                            73
 Dominican-Republic               70
 Vietnam                          67
 Guatemala                        64
 Japan                            62
 Poland                           60
 Columbia                         59
 Taiwan                           51
 Haiti                            44
 Iran                             43
 Portugal                         37
 Nicaragua                        34
 Peru                             31
 

In [12]:
adult_df.shape

(32561, 15)

In [13]:
adult_df.drop('fnlwgt', axis=1, inplace=True)

In [14]:
adult_df.shape

(32561, 14)

In [15]:
age_mask = (adult_df.age > 70)
female_mask = (adult_df.sex == ' Female')
women_over_70 = age_mask & female_mask
(adult_df[age_mask & female_mask].shape, 
 adult_df[women_over_70].shape)

((181, 14), (181, 14))

In [16]:
test_df = adult_df[(missing_workclass | 
                    missing_occupation | 
                    missing_native_country)]

In [17]:
test_df.shape

(2399, 14)

In [18]:
test_df.index[:10]

Int64Index([14, 27, 38, 51, 61, 69, 77, 93, 106, 128], dtype='int64')

In [19]:
training_df = adult_df[~(missing_workclass | 
                         missing_occupation | 
                         missing_native_country)].copy()

In [20]:
training_df.shape

(30162, 14)

In [21]:
training_df.index[10:20]

Int64Index([10, 11, 12, 13, 15, 16, 17, 18, 19, 20], dtype='int64')

In [22]:
target_workclass      = training_df.workclass
target_occupation     = training_df.occupation
target_native_country = training_df.native_country

In [23]:
training_df.drop(['workclass',
                  'occupation',
                  'native_country',
                  'income_class'], axis=1, inplace=True)

In [24]:
training_df.shape

(30162, 10)

In [25]:
training_df.dtypes

age                int64
education         object
education_num      int64
marital_status    object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
dtype: object

In [26]:
numerical_features = ['age', 'capital_gain', 'capital_loss', 'hours_per_week']
training_df = training_df[numerical_features]
test_df = test_df[numerical_features]

In [27]:
training_df.shape, test_df.shape

((30162, 4), (2399, 4))

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
target_workclass.unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' Self-emp-inc', ' Without-pay'], dtype=object)

In [60]:
le_workclass = LabelEncoder()
le_occupation = LabelEncoder()
le_native_country = LabelEncoder()
target_workclass = le_workclass.fit_transform(target_workclass)
target_occupation = le_occupation.fit_transform(target_occupation)
target_native_country = le_native_country.fit_transform(target_native_country)

In [61]:
(target_workclass.shape,
 target_occupation.shape,
 target_native_country.shape,
training_df.shape,
test_df.shape)

((30162,), (30162,), (30162,), (30162, 4), (2399, 4))

In [62]:
from sklearn.ensemble import GradientBoostingClassifier

In [63]:
model_workclass      = GradientBoostingClassifier()
model_occupation     = GradientBoostingClassifier()
model_native_country = GradientBoostingClassifier()

In [ ]:
model_workclass.fit(training_df, target_workclass)
model_occupation.fit(training_df, target_occupation)
model_native_country.fit(training_df, target_native_country)

In [56]:
test_workclass = model_workclass.predict(test_df)
test_occupation = model_occupation.predict(test_df)
test_native_country = model_native_country.predict(test_df)

In [58]:
test_workclass = le_workclass.inverse_transform(test_workclass)
test_occupation = le_occupation.inverse_transform(test_occupation)
test_native_country = le_native_country.inverse_transform(test_native_country)

/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [59]:
test_workclass

array([2, 2, 2, ..., 2, 2, 2])

In [43]:
test_workclass = pd.Series(, index=test_df.index)
test_occupation = pd.Series(, index=test_df.index)
test_native_country = pd.Series(, index=test_df.index)

In [44]:
(test_workclass.shape,
 test_occupation.shape,
 test_native_country.shape)

((2399,), (2399,), (2399,))

In [45]:
test_workclass.index

Int64Index([   14,    27,    38,    51,    61,    69,    77,    93,   106,
              128,
            ...
            32490, 32492, 32494, 32510, 32525, 32530, 32531, 32539, 32541,
            32542],
           dtype='int64', length=2399)

In [53]:
adult_df.workclass.mask(missing_workclass, test_workclass)

0                State-gov
1         Self-emp-not-inc
2                  Private
3                  Private
4                  Private
5                  Private
6                  Private
7         Self-emp-not-inc
8                  Private
9                  Private
10                 Private
11               State-gov
12                 Private
13                 Private
14                 Private
15                 Private
16        Self-emp-not-inc
17                 Private
18                 Private
19        Self-emp-not-inc
20                 Private
21                 Private
22             Federal-gov
23                 Private
24                 Private
25               Local-gov
26                 Private
27                       2
28                 Private
29                 Private
               ...        
32531                    2
32532              Private
32533              Private
32534              Private
32535              Private
32536              Private
3

In [51]:
adult_df.test_workclass.loc[:20], adult_df.workclass.loc[:20]

(0     NaN
 1     NaN
 2     NaN
 3     NaN
 4     NaN
 5     NaN
 6     NaN
 7     NaN
 8     NaN
 9     NaN
 10    NaN
 11    NaN
 12    NaN
 13    NaN
 14    2.0
 15    NaN
 16    NaN
 17    NaN
 18    NaN
 19    NaN
 20    NaN
 Name: test_workclass, dtype: float64, 0             State-gov
 1      Self-emp-not-inc
 2               Private
 3               Private
 4               Private
 5               Private
 6               Private
 7      Self-emp-not-inc
 8               Private
 9               Private
 10              Private
 11            State-gov
 12              Private
 13              Private
 14              Private
 15              Private
 16     Self-emp-not-inc
 17              Private
 18              Private
 19     Self-emp-not-inc
 20              Private
 Name: workclass, dtype: object)

In [46]:
adult_df[missing_workclass].workclass 

/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:4401: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [40]:
missing_occupation
missing_native_country

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14        True
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...  
32531    False
32532    False
32533    False
32534    False
32535    False
32536    False
32537    False
32538    False
32539    False
32540    False
32541    False
32542    False
32543    False
32544    False
32545    False
32546    False
32547    False
32548    False
32549    False
32550    False
32551    False
32552    False
32553    False
32554    False
32555    False
32556    False
32557    False
32558    False
32559    False
32560    False
Name: native_country, Length: 32561, dtype: bool